name: Branch Deleter

on:
  pull_request:
    types: [ closed ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  delete-branch:
    # Check whether the PR was authored by 'sahanruwanga'
    if: github.event.pull_request.head.repo.owner.login == 'sahanruwang'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Delete PR Branch for Hotfix delivery
        run: git push -d origin ${{ github.event.pull_request.head.ref }}
        
